services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: evm-balances-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
      VITE_BACKEND_URL: http://localhost:8000/
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: evm-balances-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_LOG_LEVEL=debug
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge