services:
  frontend:
    build:
      target: development
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      HOST: ${HOST:-http://localhost}
    volumes:
      - ./frontend:/app

  backend:
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_LOG_LEVEL=debug
    command: uvicorn app:app --reload
